[package]
name = "fstree"
version = "0.1.0"
edition = "2024"
authors = ["Shresht7"]
description = "list contents of a directory in a tree format"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
ignore = "0.4.23"
